### ISSUE TITLE
Not activated

### ISSUE THREAD

**Issue by SKILHUNT** [11notes/docker-kms#10]
Use instrucrion but get this log and system not activeted.

Fri, 07 Feb 2025 12:29:24 INFO     Connection accepted: 192.168.1.43:50322
Fri, 07 Feb 2025 12:29:24 INFO     RPC bind request received.
Fri, 07 Feb 2025 12:29:24 INFO     RPC bind acknowledged.
Fri, 07 Feb 2025 12:29:24 INFO     Received activation request.
Fri, 07 Feb 2025 12:29:24 INFO     Received V6 request on Fri Feb 07 12:29:24 2025.
Fri, 07 Feb 2025 12:29:24 WARNING  With count = 26, activated client could be detected as not genuine !
Fri, 07 Feb 2025 12:29:24 INFO     Machine Name: DESKTOP-FI4NPDI
Fri, 07 Feb 2025 12:29:24 INFO     Client Machine ID: 68b66080-8f6f-4574-a489-73d5f39fb7cb
Fri, 07 Feb 2025 12:29:24 INFO     Application ID: Windows
Fri, 07 Feb 2025 12:29:24 INFO     SKU ID: Windows 10/11 Professional
Fri, 07 Feb 2025 12:29:24 INFO     License Status: Notifications Mode
Fri, 07 Feb 2025 12:29:24 INFO     Request Time: 2025-02-07 08:29:21 CET (UTC+0100)
Fri, 07 Feb 2025 12:29:24 INFO     Connection closed: 192.168.1.43:50322

**Comment by Hobbabobba** [comment]
I have the same problem. My `docker-compose.yml`

```
name: "kms"
services:
  kms:
    image: "11notes/kms:646f476"
    container_name: "kms"
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "var:/kms/var"
    ports:
      - "1688:1688/tcp"
    restart: "always"
  kms-gui:
    image: "11notes/kms-gui:latest"
    container_name: "kms-gui"
    environment:
      TZ: "Europe/Berlin"
    volumes:
      - "var:/kms/var"
    ports:
      - "8081:8080/tcp"
    restart: "always"
volumes:
  var:
```
My logfile:
```
2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z type=INF 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z 2025-02-07T12:40:32.000Z type=INF msg=starting kms v646f476
Fri, 07 Feb 2025 13:40:32 WARNING  IPv4 [0.0.0.0] can't be dualstack
Fri, 07 Feb 2025 13:40:32 INFO     TCP server listening at 0.0.0.0 on port 1688
Fri, 07 Feb 2025 13:40:32 INFO     HWID: 8706299C48714246
Fri, 07 Feb 2025 13:41:18 INFO     Connection accepted: 192.168.0.131:57814
Fri, 07 Feb 2025 13:41:18 INFO     RPC bind request received.
Fri, 07 Feb 2025 13:41:18 INFO     RPC bind acknowledged.
Fri, 07 Feb 2025 13:41:18 INFO     Received activation request.
Fri, 07 Feb 2025 13:41:18 INFO     Received V6 request on Fri Feb 07 13:41:18 2025.
Fri, 07 Feb 2025 13:41:18 WARNING  Too many clients ! Fixed with 10
Fri, 07 Feb 2025 13:41:18 INFO     Machine Name: LAPTOP-14LAC5FN
Fri, 07 Feb 2025 13:41:18 INFO     Client Machine ID: 5bbea8ee-7e91-41f9-bb36-652e4bc96fe3
Fri, 07 Feb 2025 13:41:18 INFO     Application ID: Office 15 (2013) / 16 (2016) / 17 (2019)
Fri, 07 Feb 2025 13:41:18 INFO     SKU ID: Office Standard 2019
Fri, 07 Feb 2025 13:41:18 INFO     License Status: Activated
Fri, 07 Feb 2025 13:41:18 INFO     Request Time: 2025-02-07 12:41:18 CET (UTC+0100)
Fri, 07 Feb 2025 13:41:18 INFO     Connection closed: 192.168.0.131:57814
```
On the clientside i get this error message:
```
