### ISSUE TITLE
Does not run on unraid

### ISSUE THREAD

**Issue by marlowleon** [11notes/docker-kms#12]
App stays in the stopped status on unraid, cannot pull any logs either. has this been reported?

**Comment by 11notes** [comment]
Unraid uses UID/GID 99:100 as far as I know to run containers. My container images all come by default as 1000:1000. I don’t use unraid myself so I’m not aware how you can change to run a container image as 1000:1000 instead of 99:100.

**Comment by steckums** [comment]
You can specify the user in the docker-compose file with `user: 99:100` or specifying the PUID and PGID environment variables. Both are below.

```
  kms:
    image: "11notes/kms:465f4d1"
    container_name: "kms"
    user: 99:100
    environment:
     - PUID=99
     - PGID=100
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "var:/kms/var"
    ports:
      - "1688:1688/tcp"
    restart: "always"

```
