### ISSUE TITLE
Anyone run this in Kubernetes?

### ISSUE THREAD

**Issue by frobobbo** [11notes/docker-kms#13]
I don't have much to go on - I am able to deploy the container, but it crashes and restarts.  The only thing in the logs is:
{"time":"2025-02-11T21:39:12.000Z","type":"INF","msg":"starting kms v465f4d1"}

Nothing else.

**Comment by 11notes** [comment]
The image has a volume so you need a PVC, did you setup a PVC for the /kms/var volume?

**Comment by frobobbo** [comment]
yes, the PVC an SVC were created successfully, and the PVC was mounted to /kms/var.  I tried enabling DEBUG logging, but I can't find any other information to go on after the single LOG I pasted in the first comment

**Comment by frobobbo** [comment]
Here is my yaml:
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kms-pvc
  labels:
    app: kms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kms
  labels:
    app: kms
spec:
  ports:
  - name: "kms"
    port: 1688
    targetPort: 1688
  selector:
    app: kms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kms
  name: kms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kms
  template:
    metadata:
      labels:
        app: kms
    spec:
      containers:
      - name: kms
        image: 11notes/kms:465f4d1
        imagePullPolicy: Always
        ports:
        - containerPort: 1688
        volumeMounts:
        - name: kms-pvc
          mountPath: /kms/var
        env:
        - name: TZ
          value: "America/Detroit"
        - name: DEBUG
        - name: KMS_LOGLEVEL
          value: DEBUG
      volumes:
      - name: kms-pvc
        persistentVolumeClaim:
          claimName: kms-pvc`

**Comment by CyberAustin** [comment]
I just deployed this manifest and it appears to be working. Probably need to adjust the pvc storage class to suit your cluster. Haven't tried to activate anything, because I'm sitting in an airport, but all the containers in the pod are running and the gui is accessible. 

``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kms-pvc
  namespace: kms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms
  namespace: kms
  labels:
    app: kms
spec:
  selector:
    matchLabels:
      app: kms
  replicas: 1
  template:
    metadata:
      name: kms
      namespace: kms
      labels:
        app: kms
    spec:
      volumes:
      - name: kms-var
        persistentVolumeClaim:
          claimName: kms-pvc
      containers:
      - name: kms
        image: 11notes/kms:465f4d1
        volumeMounts:
        - name: kms-var
          mountPath: /var/kms
        ports:
        - containerPort: 1688
        env:
        - name: TZ
          value: Europe/Berlin
      - name: kms-gui
        image: 11notes/kms-gui:stable
        volumeMounts:
        - name: kms-var
          mountPath: /var/kms
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Europe/Berlin
---
apiVersion: v1
kind: Service
metadata:
  name: kms-service
  namespace: kms
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: kms
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kms-ingress
  namespace: kms
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - kms.[redacted].net
    secretName: kms-cert
  rules:
    - host: kms.[redacted].net
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kms-service
              port:
                number: 8080
```

**Comment by CyberAustin** [comment]
> ## Here is my yaml:
> `
> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
> name: kms-pvc
> labels:
> app: kms
> spec:
> accessModes:
> - ReadWriteOnce
> resources:
> requests:
> storage: 1Gi
> 
> apiVersion: v1 kind: Service metadata: name: kms labels: app: kms spec: ports:
> 
>     * name: "kms"
>       port: 1688
>       targetPort: 1688
>       selector:
>       app: kms
> 
> 
> apiVersion: apps/v1 kind: Deployment metadata: labels: app: kms name: kms spec: replicas: 1 selector: matchLabels: app: kms template: metadata: labels: app: kms spec: containers: - name: kms image: 11notes/kms:465f4d1 imagePullPolicy: Always ports: - containerPort: 1688 volumeMounts: - name: kms-pvc mountPath: /kms/var env: - name: TZ value: "America/Detroit" - name: DEBUG - name: KMS_LOGLEVEL value: DEBUG volumes: - name: kms-pvc persistentVolumeClaim: claimName: kms-pvc `

Try putting your code inbetween blocks of ``` to have it retain the format in a multi-line

**Comment by CyberAustin** [comment]
Created a pull request here: https://github.com/11notes/docker-kms/pull/21 to helpfully guide others to the k8s light

**Comment by CyberAustin** [comment]
I was too hasty, as only the webui is working. I haven't found a good way to get the activation working just yet.

**Comment by 11notes** [comment]
@CyberAustin thanks for supporting @frobobbo.

**Comment by CyberAustin** [comment]
Since this isn't going to be merged, I'm going to leave a complete manifest file here, to help anyone in the future get started.

``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kms-pvc
  namespace: kms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn #Change to whatever storage class you're using, if needed
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms
  namespace: kms
  labels:
    app: kms
spec:
  selector:
    matchLabels:
      app: kms
  replicas: 1
  template:
    metadata:
      name: kms
      namespace: kms
      labels:
        app: kms
    spec:
      volumes:
      - name: kms-var
        persistentVolumeClaim:
          claimName: kms-pvc
      containers:
      - name: kms
        image: 11notes/kms:465f4d1
        volumeMounts:
        - name: kms-var
          mountPath: /var/kms
        ports:
        - containerPort: 1688
        env:
        - name: TZ
          value: Europe/Berlin #Adjust to your local timezone
      - name: kms-gui
        image: 11notes/kms-gui:stable
        volumeMounts:
        - name: kms-var
          mountPath: /var/kms
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Europe/Berlin #Adjust to your local timezone
---
apiVersion: v1
kind: Service
metadata:
  name: kms-webui-svc
  namespace: kms
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: kms
---
apiVersion: v1
kind: Service
metadata:
  name: kms-svc
  namespace: kms
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.210 #adjust to fit your environment
  ports:
  - port: 1688
    targetPort: 1688
    protocol: TCP
  selector:
    app: kms
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kms-ingress
  namespace: kms
  annotations: #You can delete this annotation if you're not using cert-manager
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls: #You can delete this tls block if you're not using tls
  - hosts:
    - kms.example.com
    secretName: kms-cert
  rules:
    - host: kms.example.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kms-service
              port:
                number: 8080
```
