### ISSUE TITLE
Healthcheck fails

### ISSUE THREAD

**Issue by holmes111** [11notes/docker-kms#20]
The activation works

The health checks unfortunately not. In a previous version, it worked

My docker-compose.yml:
```
---
name: kms
services:
  kms:
    image: 11notes/kms:stable
    container_name: kms
    environment:
      TZ: Europe/Berlin
    volumes:
      - var:/kms/var
    ports:
      - 1688:1688/tcp
    restart: always
  kms-gui:
    image: 11notes/kms-gui:stable
    container_name: kms-gui
    environment:
      TZ: Europe/Berlin
    volumes:
      - var:/kms/var
    ports:
      - 8080:8080/tcp
    restart: always
volumes:
  var:

```

docker logs kms
```
Fri, 14 Feb 2025 08:15:20 WARNING  IPv4 [0.0.0.0] can't be dualstack
Fri, 14 Feb 2025 08:15:20 INFO     TCP server listening at 0.0.0.0 on port 1688
Fri, 14 Feb 2025 08:15:20 INFO     HWID: xxx
Fri, 14 Feb 2025 08:21:39 INFO     Connection accepted: 10.x.y.z:53609
Fri, 14 Feb 2025 08:21:39 INFO     RPC bind request received.
Fri, 14 Feb 2025 08:21:39 INFO     RPC bind acknowledged.
Fri, 14 Feb 2025 08:21:39 INFO     Received activation request.
Fri, 14 Feb 2025 08:21:39 INFO     Received V6 request on Fri Feb 14 08:21:39 2025.
Fri, 14 Feb 2025 08:21:39 WARNING  Too many clients ! Fixed with 10
Fri, 14 Feb 2025 08:21:39 INFO     Machine Name: xyz
Fri, 14 Feb 2025 08:21:39 INFO     Client Machine ID: abc
Fri, 14 Feb 2025 08:21:39 INFO     Application ID: Office 2013 / 2016 / 2019 / LTSC 2021 / LTSC 2024
Fri, 14 Feb 2025 08:21:39 INFO     SKU ID: Office LTSC Professional Plus 2024
Fri, 14 Feb 2025 08:21:39 INFO     License Status: Activated
Fri, 14 Feb 2025 08:21:39 INFO     Request Time: 2025-02-14 07:21:34 CET (UTC+0100)
Fri, 14 Feb 2025 08:21:39 INFO     Server ePID: xyz
Fri, 14 Feb 2025 08:21:39 INFO     KMS V6 Response: 

                                   ResponseV5
                                   bodyLength1: {260}
                                   bodyLength2: {260}
                                   versionMinor: {0}
                                   versionMajor: {6}
                                   salt: removed

Fri, 14 Feb 2025 08:21:39 INFO     KMS V6 Structure Bytes: 

                                   0123

Fri, 14 Feb 2025 08:21:39 INFO     Responded to activation request.
Fri, 14 Feb 2025 08:21:39 INFO     Connection closed: 10.x.y.z:53609

```

docker ps -a
```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                     PORTS                                                NAMES
a5fa90f58b56   11notes/kms-gui:stable   "/sbin/tini -- /usr/…"   4 minutes ago    Up 4 minutes (healthy)     0.0.0.0:8080->8080/tcp, :::8080->8080/tcp            kms-gui
98d6e46f0e0a   11notes/kms:stable       "/sbin/tini -- /usr/…"   4 minutes ago    Up 4 minutes (unhealthy)   0.0.0.0:1688->1688/tcp, :::1688->1688/tcp            kms

```

My setup:
```
Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.1.0-31-amd64
    Architecture: x86-64
```
docker version
```
Client: Docker Engine - Community
 Version:           27.5.1
 API version:       1.47
 Go version:        go1.22.11
 Git commit:        9f9e405
 Built:             Wed Jan 22 13:41:17 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.5.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.11
  Git commit:       4c9b3b0
  Built:            Wed Jan 22 13:41:17 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
