### ISSUE TITLE
Module 'tzlocal' or 'pytz' not available ! Request time not localized.

### ISSUE THREAD

**Issue by PsychotherapistSam** [11notes/docker-kms#7]
Hello,

when setting up the container, I get the following errors after trying to activate a client.
The kms server is behind a reverse proxy, but that shouldn't be an issue.
I tried setting the Timezone with the env var as well as mounting /etc/localtime, but with no luck:
```
kms      | Thu, 06 Feb 2025 15:17:17 INFO     Connection accepted: 192.168.1.52:57680
kms      | Thu, 06 Feb 2025 15:17:17 INFO     RPC bind request received.
kms      | Thu, 06 Feb 2025 15:17:17 INFO     RPC bind acknowledged.
kms      | Thu, 06 Feb 2025 15:17:17 INFO     Received activation request.
kms      | Thu, 06 Feb 2025 15:17:17 INFO     Received V6 request on Thu Feb 06 15:17:17 2025.
kms      | Thu, 06 Feb 2025 15:17:17 WARNING  Module 'tzlocal' or 'pytz' not available ! Request time not localized.
kms      | Thu, 06 Feb 2025 15:17:17 WARNING  With count = 25, activated client could be detected as not genuine !
kms      | Thu, 06 Feb 2025 15:17:17 INFO     Connection closed: 192.168.1.52:57680
```
Commands used on Windows Client:
```
$ slmgr /skms kms.domain.tld
$ slmgr /ipk W269N-WFGWX-YVC9B-4J6C9
$ slmgr /ato
```
Compose File:
```
name: kms
services:
  kms:
    image: 11notes/kms:latest
    container_name: kms
    volumes:
      - ./kms:/kms/var
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1688:1688/tcp
    restart: always
  kms-gui:
    image: 11notes/kms-gui:646f476
    container_name: kms-gui
    volumes:
      - ./kms_gui:/kms/var
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6630:8080/tcp
    restart: always
networks: {}
```
The permissions for the container's folders are set correctly.
